---
title: "Playlist Summary for 'Sophisticated Boom Boom' on WFMU"
author: "Art Steinmetz"
date: "January 2022"
output:
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
# pulled from YAML Header
#date: "`r format(Sys.Date(), "%B %d, %Y")`"

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lubridate)
library(xts)
library(knitr)
library(remotes)
library(gt)

load(file='data/playlists.rdata')
```
# Top Songs for Sophisticated Boom Boom, Last 12 Months
```{r echo=FALSE, message=FALSE, warning=FALSE}

# not run because no song is played more than once

sblists <- playlists %>% filter(DJ=="CF") %>% 
  mutate(artist_song = paste(ArtistToken,Title,sep=" - "))

write_csv(sblists,"sblists.csv")
sblists <- ungroup(sblists)
sblists <- sblists %>% 
  # limit to whole months
  filter(AirDate<floor_date(Sys.Date(),unit="months")) %>% 
  mutate(year_month=as.yearmon(AirDate))

sblists %>% 
  #limit top songs to last 12 months
  filter(AirDate > Sys.Date()-365) %>% 
  group_by(artist_song) %>% 
  summarise(PlayCount=n(),.groups="keep") %>%
#  group_by(year_month) %>% 
#  top_n(10,top_songs) %>% 
  filter(PlayCount > 1) %>% 
  arrange(desc(PlayCount)) %>% 
#  slice_max(top_songs,n=20,with_ties = FALSE) %>% 
gt::gt(groupname_col = "year_month") %>%
cols_merge(vars(artist_song,PlayCount),pattern="{1} - {2}") %>%
cols_label(artist_song= md("**Artist - Song - Play Count**")) %>%
tab_style(style = list(cell_text(weight = "bold",
                                 size = "large",style="italic")),
          locations = cells_row_groups()) %>%
  {.}
  
```
\newpage
# Top Artists for Sophisticated Boom Boom, Last 12 Months
```{r echo=FALSE, message=FALSE}
sblists %>%
  #limit top songs to last 12 months
  filter(AirDate > Sys.Date()-365) %>% 
  group_by(Artist) %>% 
  summarise(top_artists=n(),.groups="keep") %>% 
  ungroup() %>% 
  slice_max(top_artists,n=10,with_ties = T) %>% 
  gt::gt(groupname_col = "year_month") %>%
  cols_merge(c(Artist,top_artists),pattern="{1} - {2}") %>%
  cols_label(Artist= md("**Artist - Play Count**")) %>% 
  tab_style(style = list(cell_text(weight = "bold",size = "large",style="italic")),
            locations = cells_row_groups()) %>% 
  {.}

```
\newpage
# Top 40 Songs of All Time for Sophisticated Boom Boom

```{r echo=FALSE, message=FALSE}
sblists %>% 
  group_by(artist_song) %>% 
  summarise(top_songs=n()) %>% 
  arrange(desc(top_songs)) %>% 
  top_n(40,wt=top_songs) %>% 
  gt::gt() %>% cols_merge(c(artist_song,top_songs),
                          pattern="{1} - {2}") %>% 
  cols_label(artist_song= md("**Artist - Song - Play Count**"))

```

\newpage
# Top 40 Artists of All Time for Sophisticated Boom Boom

```{r echo=FALSE, message=FALSE}
sblists %>% 
  group_by(Artist) %>% 
  summarise(top_songs=n()) %>% 
  arrange(desc(top_songs)) %>% 
  top_n(40,wt=top_songs) %>% 
  gt::gt() %>% cols_merge(c(Artist,top_songs),
                          pattern="{1} - {2}") %>% 
  cols_label(Artist= md("**Artist - Play Count**"))

```


